# Setup
title:               herehyunBlog
tagline:             '시작의 블로그'
description:         '데이터 분석 시작의 블로그입니다.'
url:                 https://herehyun.github.io/hereblog.github.io/
baseurl:             https://herehyun.github.io/hereblog.github.io/
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Yeo GiHyun
  url:               https://github.com/herehyun
  email:             yeo0109@naver.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
